### ISSUE TITLE
Laravel Sail guide 

### ISSUE THREAD

**Issue by matsava** [renoki-co/clusteer#41]
Would it be possible to have documentation on how to set this up with Laravel Sail or possibly a demo repository?

**Comment by rennokki** [comment]
I will update the documentation for this. 😺

Basically, you may add this to your `docker-compose.yaml`:

```yaml
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    # ...

    clusteer:
        image: 'quay.io/renokico/clusteer:3.0-16-alpine'
        environment:
            DEBUG: '1'
            MAX_BROWSERS: '1'
        ports:
            - '${CLUSTEER_PORT:-8080}:8080'
        networks:
            - sail

networks:
    sail:
        driver: bridge
```
